export const messages = [
    {
      _id: 1,
      avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
      fullName: 'John Doe',
      recentText: 'Buy some milk for me',
      timeStamp: '4:45 PM',
      messageCount: 5,
      online: true
    },
    {
      _id: 2,
      avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
      fullName: 'Jane Smith',
      recentText: "Sure, I'll grab it on my way home.",
      timeStamp: '5:15 PM',
      messageCount: 2,
      online: false
    },
    {
      _id: 3,
      avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
      fullName: 'Bob Johnson',
      recentText: 'Meeting at 2 PM tomorrow, be prepared!',
      timeStamp: '8:30 AM',
      messageCount: 2,
      online: true

    },
    {
      _id: 4,
      avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
      fullName: 'Alice Williams',
      recentText: 'Just finished reading a great book!',
      timeStamp: '11:20 AM',
      messageCount: 0,
      online: false
    },
    {
      _id: 5,
      avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
      fullName: 'Samuel Brown',
      recentText: 'What are your plans for the weekend?',
      timeStamp: '2:50 PM',
      messageCount: 4,
      online: true
    },
    {
        _id: 6,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Eva Johnson',
        recentText: 'Just got back from vacation!',
        timeStamp: '3:30 PM',
        messageCount: 3,
        online: false,
      },
      {
        _id: 7,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Max Williams',
        recentText: 'Working on a new project.',
        timeStamp: '9:15 AM',
        messageCount: 0,
        online: true,
      },
      {
        _id: 8,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Eva Johnson',
        recentText: 'Just got back from vacation!',
        timeStamp: '3:30 PM',
        messageCount: 3,
        online: false,
      },
      {
        _id: 9,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Max Williams',
        recentText: 'Working on a new project.',
        timeStamp: '9:15 AM',
        messageCount: 0,
        online: true,
      },
      {
        _id: 10,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Eva Johnson',
        recentText: 'Just got back from vacation!',
        timeStamp: '3:30 PM',
        messageCount: 3,
        online: false,
      },
      {
        _id: 11,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Max Williams',
        recentText: 'Working on a new project.',
        timeStamp: '9:15 AM',
        messageCount: 0,
        online: true,
      },
      {
        _id: 12,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Eva Johnson',
        recentText: 'Just got back from vacation!',
        timeStamp: '3:30 PM',
        messageCount: 3,
        online: false,
      },
      {
        _id: 13,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Max Williams',
        recentText: 'Working on a new project.',
        timeStamp: '9:15 AM',
        messageCount: 0,
        online: true,
      },
      {
        _id: 14,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Eva Johnson',
        recentText: 'Just got back from vacation!',
        timeStamp: '3:30 PM',
        messageCount: 3,
        online: false,
      },
      {
        _id: 15,
        avatarUrl: 'https://res.cloudinary.com/dyeftbxjw/image/upload/v1704140193/avatar/default.png',
        fullName: 'Max Williams',
        recentText: 'Working on a new project.',
        timeStamp: '9:15 AM',
        messageCount: 0,
        online: true,
      },
  ];
  
